### ISSUE TITLE
Errors in example

### ISSUE THREAD

**Issue by twodayslate** [nidhaloff/b_rabbit#1]
* b_rabbit version: master
* Python version: 3.8.1
* Operating System: macOS

### Description

Running the scripts in the example in the README I get the following error 

```
Task Response received
bytearray(b'return this value to requester')
Traceback (most recent call last):
  File "./requster.py", line 16, in <module>
    rabbit.close_connection()
  File "/Users/zrgorak/Development/b_rabbit/b_rabbit/b_rabbit.py", line 50, in close_connection
    self._shutdown_gracefully()
  File "/Users/zrgorak/Development/b_rabbit/b_rabbit/b_rabbit.py", line 60, in _shutdown_gracefully
    activeQueue.stop_consuming()
  File "/Users/zrgorak/.pyenv/versions/b_rabbit/lib/python3.8/site-packages/rabbitpy/amqp_queue.py", line 342, in stop_consuming
    raise exceptions.NotConsumingError()
rabbitpy.exceptions.NotConsumingError: No active consumer to cancel
```

```
% pip freeze 
appdirs==1.4.4
b-rabbit @ file:///Users/zrgorak/Development/b_rabbit
distlib==0.3.1
filelock==3.0.12
packaging==20.4
pamqp==2.3.0
pluggy==0.13.1
py==1.9.0
pyparsing==2.4.7
rabbitpy==2.0.1
six==1.15.0
toml==0.10.1
tox==3.19.0
virtualenv==20.0.30
```

Seems like you either have to check if the queue is consuming or just wrap in a try catch

**Comment by nidhaloff** [comment]
Thanks for noticing this. Actually, I forgot to push changes I made at that time. I will fix this now

**Comment by twodayslate** [comment]
Not sure if I should create a new issue for this but I noticed that https://github.com/nidhaloff/b_rabbit/blob/master/b_rabbit/b_rabbit.py#L376
returns True but if the with fails the default return value is None. Also I don't understand why there is a for loop when the first value returns True no matter what

**Comment by nidhaloff** [comment]
You are right there should be no return there. I played with the code sometime and forgot to checkout these changes! Thanks for creating the issue. Feel free to make a pull request If you can see any improvement ;)
